"""Strategy Execution Engine for TraderClaw.

This module provides the core strategy execution capabilities:
- Plain language strategy interpretation via LLM
- Technical indicator integration
- Multi-model consensus (DeepSeek + Qwen)
- Hybrid approval flow (auto-execute vs ask user)
- Multi-account support for strategy comparison
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Any, Callable
from pathlib import Path
import yaml
import json
import asyncio

from ..ai.strategy_agents import (
    StrategyAgent,
    StrategyModel,
    StrategyAgentFactory,
    TradingDecision,
)
from ..ai.gemini_data_agent import GeminiDataAgent, MarketDataPackage
from ..indicators.technical import IndicatorCalculator, get_indicator_calculator
from ..infrastructure.brokers import get_broker_manager

logger = logging.getLogger(__name__)


class ApprovalMode(Enum):
    """Strategy approval modes."""
    AUTONOMOUS = "autonomous"  # Auto-execute all signals
    HYBRID = "hybrid"          # Auto if confidence high, ask if low
    APPROVAL = "approval"      # Ask for all signals
    NOTIFY = "notify"          # Just notify, no execution


class ConsensusType(Enum):
    """Multi-model consensus types."""
    UNANIMOUS = "unanimous"    # All models must agree
    MAJORITY = "majority"      # Majority rules
    WEIGHTED = "weighted"      # Weighted by model confidence
    ANY = "any"                # Any model can trigger (for redundancy)


@dataclass
class PlainLanguageStrategy:
    """A trading strategy defined in plain English.

    Instead of coding rules, users describe their strategy naturally.
    The LLM interprets this description along with market data.
    """
    id: str
    name: str
    description: str  # Plain language strategy description
    symbols: List[str]  # Symbols to monitor
    timeframe: str  # "1m", "5m", "15m", "1h", "4h", "1d"

    # Risk management (plain language)
    position_sizing: str = "equal weight"  # e.g., "5% of portfolio", "risk $100 per trade"
    max_positions: int = 5
    stop_loss_rule: Optional[str] = None  # e.g., "-5% or -2 ATR"
    take_profit_rule: Optional[str] = None  # e.g., "2:1 risk/reward"

    # Execution settings
    approval_mode: ApprovalMode = ApprovalMode.HYBRID
    auto_execute_confidence_threshold: float = 0.8  # Auto-execute if confidence >= this

    # Multi-model consensus
    use_consensus: bool = True
    consensus_type: ConsensusType = ConsensusType.WEIGHTED
    consensus_models: List[StrategyModel] = field(default_factory=lambda: [
        StrategyModel.DEEPSEEK, StrategyModel.QWEN
    ])
    model_weights: Dict[str, float] = field(default_factory=lambda: {
        "deepseek": 0.6,
        "qwen": 0.4,
    })

    # Technical indicators to include
    indicators: List[str] = field(default_factory=lambda: [
        "price", "sma_20", "sma_50", "rsi_14", "volume", "macd", "bb_position"
    ])

    # Metadata
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    enabled: bool = True
    tags: List[str] = field(default_factory=list)


@dataclass
class ConsensusResult:
    """Result of multi-model consensus analysis."""
    decisions: Dict[str, TradingDecision]
    consensus_recommendation: str
    consensus_confidence: float
    confidence_score: float  # 0-1 aggregated confidence
    agreement_level: float  # 0-1 how much models agree
    rationale: str
    primary_model: str


@dataclass
class StrategySignal:
    """A trading signal generated by a strategy."""
    strategy_id: str
    strategy_name: str
    symbol: str
    timestamp: datetime

    # Signal details
    action: str  # BUY, SELL, HOLD, PARTIAL_BUY, PARTIAL_SELL
    quantity: Optional[float]
    quantity_type: str
    confidence: float  # 0-1

    # Analysis
    rationale: str
    technical_context: str  # Formatted indicator values
    market_context: Dict[str, Any]

    # Consensus info
    consensus_result: Optional[ConsensusResult] = None

    # Execution
    approved: Optional[bool] = None  # None = pending
    executed: bool = False
    execution_result: Optional[Dict] = None
    execution_account: Optional[str] = None


@dataclass
class ExecutionPlan:
    """Execution plan for a strategy signal."""
    signal: StrategySignal
    approved: bool
    auto_approved: bool  # Was this auto-approved based on confidence?
    execution_account: str
    estimated_cost: Optional[float]
    risk_amount: Optional[float]
    notes: List[str]


class StrategyRepository:
    """Repository for storing and loading plain language strategies."""

    def __init__(self, config_dir: str = "config/strategies"):
        self.config_dir = Path(config_dir)
        self.config_dir.mkdir(parents=True, exist_ok=True)
        self._strategies: Dict[str, PlainLanguageStrategy] = {}

    def save(self, strategy: PlainLanguageStrategy) -> None:
        """Save a strategy to file."""
        filepath = self.config_dir / f"{strategy.id}.yaml"

        data = {
            "id": strategy.id,
            "name": strategy.name,
            "description": strategy.description,
            "symbols": strategy.symbols,
            "timeframe": strategy.timeframe,
            "position_sizing": strategy.position_sizing,
            "max_positions": strategy.max_positions,
            "stop_loss_rule": strategy.stop_loss_rule,
            "take_profit_rule": strategy.take_profit_rule,
            "approval_mode": strategy.approval_mode.value,
            "auto_execute_confidence_threshold": strategy.auto_execute_confidence_threshold,
            "use_consensus": strategy.use_consensus,
            "consensus_type": strategy.consensus_type.value,
            "consensus_models": [m.value for m in strategy.consensus_models],
            "model_weights": strategy.model_weights,
            "indicators": strategy.indicators,
            "enabled": strategy.enabled,
            "tags": strategy.tags,
            "created_at": strategy.created_at.isoformat(),
            "updated_at": datetime.utcnow().isoformat(),
        }

        with open(filepath, 'w') as f:
            yaml.dump(data, f, default_flow_style=False, sort_keys=False)

        self._strategies[strategy.id] = strategy
        logger.info(f"Saved strategy: {strategy.id}")

    def load(self, strategy_id: str) -> Optional[PlainLanguageStrategy]:
        """Load a strategy from file."""
        if strategy_id in self._strategies:
            return self._strategies[strategy_id]

        filepath = self.config_dir / f"{strategy_id}.yaml"
        if not filepath.exists():
            return None

        with open(filepath) as f:
            data = yaml.safe_load(f)

        strategy = self._from_dict(data)
        self._strategies[strategy_id] = strategy
        return strategy

    def load_all(self) -> List[PlainLanguageStrategy]:
        """Load all strategies."""
        strategies = []
        for filepath in self.config_dir.glob("*.yaml"):
            strategy_id = filepath.stem
            strategy = self.load(strategy_id)
            if strategy:
                strategies.append(strategy)
        return strategies

    def delete(self, strategy_id: str) -> bool:
        """Delete a strategy."""
        filepath = self.config_dir / f"{strategy_id}.yaml"
        if filepath.exists():
            filepath.unlink()
            self._strategies.pop(strategy_id, None)
            return True
        return False

    def _from_dict(self, data: Dict) -> PlainLanguageStrategy:
        """Create strategy from dictionary."""
        return PlainLanguageStrategy(
            id=data["id"],
            name=data["name"],
            description=data["description"],
            symbols=data["symbols"],
            timeframe=data["timeframe"],
            position_sizing=data.get("position_sizing", "equal weight"),
            max_positions=data.get("max_positions", 5),
            stop_loss_rule=data.get("stop_loss_rule"),
            take_profit_rule=data.get("take_profit_rule"),
            approval_mode=ApprovalMode(data.get("approval_mode", "hybrid")),
            auto_execute_confidence_threshold=data.get(
                "auto_execute_confidence_threshold", 0.8
            ),
            use_consensus=data.get("use_consensus", True),
            consensus_type=ConsensusType(data.get("consensus_type", "weighted")),
            consensus_models=[
                StrategyModel(m) for m in data.get("consensus_models", ["deepseek", "qwen"])
            ],
            model_weights=data.get("model_weights", {"deepseek": 0.6, "qwen": 0.4}),
            indicators=data.get("indicators", ["price", "rsi_14"]),
            enabled=data.get("enabled", True),
            tags=data.get("tags", []),
            created_at=datetime.fromisoformat(data["created_at"]),
            updated_at=datetime.fromisoformat(data["updated_at"]),
        )


class ConsensusEngine:
    """Multi-model consensus engine."""

    def __init__(self, api_keys: Dict[str, str]):
        """
        Initialize consensus engine.

        Args:
            api_keys: Dict mapping model names to API keys
                     e.g., {"deepseek": "sk-...", "qwen": "sk-..."}
        """
        self.api_keys = api_keys
        self._agents: Dict[str, StrategyAgent] = {}

    def _get_agent(self, model: StrategyModel) -> StrategyAgent:
        """Get or create agent for model."""
        model_key = model.value
        if model_key not in self._agents:
            api_key = self.api_keys.get(model_key)
            if not api_key:
                raise ValueError(f"No API key configured for {model_key}")
            self._agents[model_key] = StrategyAgentFactory.create(model, api_key)
        return self._agents[model_key]

    async def analyze(
        self,
        strategy: PlainLanguageStrategy,
        market_data: Dict[str, Any],
        user_context: Dict[str, Any],
        query: str
    ) -> ConsensusResult:
        """
        Run multi-model consensus analysis.

        Args:
            strategy: The strategy being evaluated
            market_data: Market data package
            user_context: User portfolio context
            query: Analysis prompt

        Returns:
            ConsensusResult with aggregated decision
        """
        # Run all models in parallel
        tasks = []
        model_names = []

        for model in strategy.consensus_models:
            try:
                agent = self._get_agent(model)
                task = agent.analyze(market_data, user_context, query)
                tasks.append(task)
                model_names.append(model.value)
            except ValueError as e:
                logger.warning(f"Skipping {model.value}: {e}")

        if not tasks:
            raise RuntimeError("No models available for consensus")

        # Gather all decisions
        results = await asyncio.gather(*tasks, return_exceptions=True)

        decisions = {}
        for name, result in zip(model_names, results):
            if isinstance(result, Exception):
                logger.error(f"Model {name} failed: {result}")
                # Create error decision
                decisions[name] = TradingDecision(
                    recommendation="HOLD",
                    symbol="UNKNOWN",
                    quantity=None,
                    quantity_type="shares",
                    confidence="low",
                    rationale=f"Error: {result}",
                    risks=["Model error"],
                    timeframe="immediate",
                )
            else:
                decisions[name] = result

        # Calculate consensus
        return self._calculate_consensus(
            decisions, strategy.consensus_type, strategy.model_weights
        )

    def _calculate_consensus(
        self,
        decisions: Dict[str, TradingDecision],
        consensus_type: ConsensusType,
        model_weights: Dict[str, float]
    ) -> ConsensusResult:
        """Calculate consensus from multiple model decisions."""

        # Count recommendations
        recommendations = [d.recommendation for d in decisions.values()]
        unique_recs = set(recommendations)

        # Calculate confidence scores (map low/medium/high to 0.0-1.0)
        confidence_map = {"low": 0.33, "medium": 0.67, "high": 1.0}

        weighted_scores = {}
        for model_name, decision in decisions.items():
            weight = model_weights.get(model_name, 1.0 / len(decisions))
            conf_score = confidence_map.get(decision.confidence, 0.5)
            weighted_scores[model_name] = conf_score * weight

        # Calculate agreement level
        if len(unique_recs) == 1:
            agreement_level = 1.0
        else:
            # Count most common
            from collections import Counter
            counts = Counter(recommendations)
            max_count = max(counts.values())
            agreement_level = max_count / len(recommendations)

        # Determine consensus recommendation
        if consensus_type == ConsensusType.UNANIMOUS:
            if len(unique_recs) == 1:
                consensus_rec = recommendations[0]
            else:
                consensus_rec = "HOLD"  # Default to hold if no unanimous

        elif consensus_type == ConsensusType.MAJORITY:
            from collections import Counter
            counts = Counter(recommendations)
            consensus_rec = counts.most_common(1)[0][0]

        elif consensus_type == ConsensusType.WEIGHTED:
            # Weight by confidence scores
            action_scores = {}
            for model_name, decision in decisions.items():
                weight = model_weights.get(model_name, 1.0)
                conf = confidence_map.get(decision.confidence, 0.5)
                score = weight * conf
                action_scores[decision.recommendation] = action_scores.get(
                    decision.recommendation, 0
                ) + score

            consensus_rec = max(action_scores, key=action_scores.get)

        else:  # ANY
            # Pick highest confidence action that's not HOLD
            best_action = "HOLD"
            best_score = 0
            for model_name, decision in decisions.items():
                if decision.recommendation != "HOLD":
                    score = weighted_scores.get(model_name, 0)
                    if score > best_score:
                        best_score = score
                        best_action = decision.recommendation
            consensus_rec = best_action

        # Calculate aggregate confidence
        avg_confidence = sum(weighted_scores.values()) / sum(model_weights.values()) if model_weights else 0.5

        # Build rationale
        parts = []
        for model_name, decision in decisions.items():
            parts.append(
                f"{model_name}: {decision.recommendation} (confidence: {decision.confidence})"
            )

        rationale = f"Consensus ({consensus_type.value}): {consensus_rec}\n"
        rationale += f"Model inputs:\n" + "\n".join(f"  - {p}" for p in parts)

        # Find primary model (highest weighted confidence for consensus action)
        primary_model = max(
            decisions.keys(),
            key=lambda m: weighted_scores.get(m, 0)
            if decisions[m].recommendation == consensus_rec else 0
        )

        return ConsensusResult(
            decisions=decisions,
            consensus_recommendation=consensus_rec,
            consensus_confidence=avg_confidence,
            confidence_score=avg_confidence,
            agreement_level=agreement_level,
            rationale=rationale,
            primary_model=primary_model,
        )


class StrategyExecutionEngine:
    """
    Main strategy execution engine.

    Combines:
    - Plain language strategy interpretation
    - Technical indicator analysis
    - Multi-model consensus
    - Hybrid approval flow
    - Multi-account execution
    """

    def __init__(
        self,
        gemini_api_key: str,
        model_api_keys: Dict[str, str],
        config_dir: str = "config/strategies"
    ):
        """
        Initialize execution engine.

        Args:
            gemini_api_key: API key for Gemini data agent
            model_api_keys: Dict of model name -> API key for consensus
            config_dir: Directory for strategy configs
        """
        self.data_agent = GeminiDataAgent(gemini_api_key)
        self.indicator_calc = get_indicator_calculator()
        self.repository = StrategyRepository(config_dir)
        self.consensus_engine = ConsensusEngine(model_api_keys)
        self.broker_manager = get_broker_manager()

        # Signal handlers
        self._approval_handlers: List[Callable[[StrategySignal], bool]] = []
        self._execution_handlers: List[Callable[[StrategySignal, ExecutionPlan], None]] = []

        logger.info("StrategyExecutionEngine initialized")

    async def evaluate_strategy(
        self,
        strategy: PlainLanguageStrategy,
        user_context: Dict[str, Any],
        account_id: Optional[str] = None
    ) -> List[StrategySignal]:
        """
        Evaluate a strategy and generate signals.

        Args:
            strategy: Strategy to evaluate
            user_context: User portfolio context
            account_id: Specific account to use (optional)

        Returns:
            List of strategy signals
        """
        if not strategy.enabled:
            logger.info(f"Strategy {strategy.id} is disabled, skipping")
            return []

        logger.info(f"Evaluating strategy: {strategy.name}")
        signals = []

        for symbol in strategy.symbols:
            try:
                signal = await self._evaluate_symbol(
                    strategy, symbol, user_context
                )
                if signal:
                    signals.append(signal)
            except Exception as e:
                logger.error(f"Failed to evaluate {symbol} for strategy {strategy.id}: {e}")

        return signals

    async def _evaluate_symbol(
        self,
        strategy: PlainLanguageStrategy,
        symbol: str,
        user_context: Dict[str, Any]
    ) -> Optional[StrategySignal]:
        """Evaluate a single symbol against a strategy."""

        # Step 1: Gather market data
        market_data_pkg = await self.data_agent.gather_market_data([symbol])

        # Step 2: Calculate technical indicators
        indicators = self.indicator_calc.calculate_all(symbol)
        technical_context = ""
        if indicators:
            technical_context = self.indicator_calc.format_for_llm(indicators)

        # Step 3: Build strategy prompt
        prompt = self._build_strategy_prompt(strategy, symbol, technical_context, user_context)

        # Step 4: Get decision (single model or consensus)
        if strategy.use_consensus and len(strategy.consensus_models) > 1:
            market_dict = self._package_for_strategy(market_data_pkg)
            consensus = await self.consensus_engine.analyze(
                strategy, market_dict, user_context, prompt
            )

            # Use consensus result
            action = consensus.consensus_recommendation
            confidence = consensus.confidence_score
            rationale = consensus.rationale
            primary_model = consensus.primary_model
            decision = consensus.decisions.get(primary_model)
        else:
            # Single model
            model = strategy.consensus_models[0] if strategy.consensus_models else StrategyModel.DEEPSEEK
            agent = self.consensus_engine._get_agent(model)
            market_dict = self._package_for_strategy(market_data_pkg)
            decision = await agent.analyze(market_dict, user_context, prompt)

            action = decision.recommendation
            confidence_map = {"low": 0.33, "medium": 0.67, "high": 1.0}
            confidence = confidence_map.get(decision.confidence, 0.5)
            rationale = decision.rationale
            consensus = None

        # Step 5: Create signal (only for actionable recommendations)
        if action in ["HOLD"]:
            return None

        signal = StrategySignal(
            strategy_id=strategy.id,
            strategy_name=strategy.name,
            symbol=symbol,
            timestamp=datetime.utcnow(),
            action=action,
            quantity=decision.quantity if decision else None,
            quantity_type=decision.quantity_type if decision else "shares",
            confidence=confidence,
            rationale=rationale,
            technical_context=technical_context,
            market_context=market_dict,
            consensus_result=consensus,
        )

        return signal

    def _build_strategy_prompt(
        self,
        strategy: PlainLanguageStrategy,
        symbol: str,
        technical_context: str,
        user_context: Dict[str, Any]
    ) -> str:
        """Build the strategy evaluation prompt."""

        prompt = f"""You are evaluating whether to trade {symbol} based on the following strategy:

## STRATEGY DESCRIPTION
{strategy.description}

## CURRENT POSITION CONTEXT
Portfolio Value: ${user_context.get('total_portfolio_value', 0):,.2f}
Cash Available: ${user_context.get('cash_available', 0):,.2f}
Current Position in {symbol}: {user_context.get('positions', {}).get(symbol, 'None')}

## TECHNICAL INDICATORS
{technical_context}

## RISK PARAMETERS
Position Sizing Rule: {strategy.position_sizing}
Stop Loss Rule: {strategy.stop_loss_rule or 'None specified'}
Take Profit Rule: {strategy.take_profit_rule or 'None specified'}
Max Positions: {strategy.max_positions}

## YOUR TASK
Based on the strategy description and current market conditions, determine if there is a trading opportunity for {symbol}.

Consider:
1. Does the strategy's entry/exit criteria match current conditions?
2. What does the technical analysis suggest?
3. Is position sizing appropriate given portfolio context?
4. Are there any upcoming events or risks to consider?

Output your decision as JSON:
{{
  "recommendation": "BUY|SELL|HOLD|PARTIAL_BUY|PARTIAL_SELL",
  "symbol": "{symbol}",
  "quantity": null or number (null to use position sizing rule),
  "quantity_type": "shares|percent_of_position|percent_of_portfolio",
  "confidence": "high|medium|low",
  "rationale": "Explain your analysis and reasoning...",
  "risks": ["risk 1", "risk 2"],
  "timeframe": "immediate|today|this_week",
  "target_price": null or number,
  "stop_loss": null or number
}}"""

        return prompt

    def _package_for_strategy(self, market_data: MarketDataPackage) -> Dict[str, Any]:
        """Convert MarketDataPackage to dict for strategy agent."""
        return {
            "timestamp": market_data.timestamp.isoformat(),
            "market_summary": market_data.market_summary,
            "symbols": {
                symbol: {
                    "price": data.price,
                    "change_24h": data.change_24h,
                    "change_1h": data.change_1h,
                    "key_news": data.key_news,
                    "upcoming_events": data.upcoming_events,
                    "sentiment": data.sentiment,
                }
                for symbol, data in market_data.symbols.items()
            },
            "polymarket_signals": market_data.polymarket_signals,
            "macro": {
                "vix": market_data.macro.vix if market_data.macro else None,
                "fed_policy": market_data.macro.fed_policy if market_data.macro else "unknown",
                "market_regime": market_data.macro.market_regime if market_data.macro else "unknown",
                "major_events": market_data.macro.major_events if market_data.macro else [],
            } if market_data.macro else None,
        }

    async def process_signal(
        self,
        signal: StrategySignal,
        strategy: PlainLanguageStrategy,
        account_id: Optional[str] = None
    ) -> ExecutionPlan:
        """
        Process a signal through approval flow.

        Args:
            signal: The strategy signal
            strategy: Parent strategy
            account_id: Account to use for execution

        Returns:
            ExecutionPlan with approval status
        """
        # Determine approval based on mode and confidence
        auto_approved = False
        approved = False
        notes = []

        if strategy.approval_mode == ApprovalMode.AUTONOMOUS:
            approved = True
            auto_approved = True
            notes.append("Auto-approved (autonomous mode)")

        elif strategy.approval_mode == ApprovalMode.NOTIFY:
            approved = False
            auto_approved = False
            notes.append("Notification only - no execution")

        elif strategy.approval_mode == ApprovalMode.HYBRID:
            if signal.confidence >= strategy.auto_execute_confidence_threshold:
                approved = True
                auto_approved = True
                notes.append(
                    f"Auto-approved (confidence {signal.confidence:.2f} >= "
                    f"threshold {strategy.auto_execute_confidence_threshold})"
                )
            else:
                approved = False
                auto_approved = False
                notes.append(
                    f"Requires approval (confidence {signal.confidence:.2f} < "
                    f"threshold {strategy.auto_execute_confidence_threshold})"
                )

        else:  # APPROVAL mode
            approved = False
            auto_approved = False
            notes.append("Requires manual approval")

        # Call approval handlers
        if not auto_approved:
            for handler in self._approval_handlers:
                result = handler(signal)
                if result:
                    approved = True
                    notes.append("Approved by user handler")
                    break

        # Determine execution account
        execution_account = account_id or "default"

        # Calculate estimated cost/risk
        estimated_cost = None
        risk_amount = None
        if signal.quantity:
            price = signal.market_context.get("symbols", {}).get(signal.symbol, {}).get("price")
            if price:
                estimated_cost = signal.quantity * price
                # Simple risk estimate (could be more sophisticated)
                risk_amount = estimated_cost * 0.05  # Assume 5% risk per trade

        plan = ExecutionPlan(
            signal=signal,
            approved=approved,
            auto_approved=auto_approved,
            execution_account=execution_account,
            estimated_cost=estimated_cost,
            risk_amount=risk_amount,
            notes=notes,
        )

        # Execute if approved
        if approved:
            await self._execute_signal(signal, plan)

        return plan

    async def _execute_signal(
        self,
        signal: StrategySignal,
        plan: ExecutionPlan
    ) -> None:
        """Execute an approved signal."""
        try:
            broker = self.broker_manager.get_broker(plan.execution_account)

            # Place order
            from ..application.interfaces.broker import Order, OrderSide, OrderType

            side = OrderSide.BUY if signal.action in ["BUY", "PARTIAL_BUY"] else OrderSide.SELL

            order = Order(
                symbol=signal.symbol,
                side=side,
                quantity=signal.quantity or 0,  # Would need proper position sizing
                order_type=OrderType.MARKET,
            )

            result = await broker.place_order(order)

            signal.executed = True
            signal.execution_result = {
                "order_id": result.order_id,
                "status": result.status.value,
                "filled_quantity": str(result.filled_quantity),
                "avg_fill_price": str(result.avg_fill_price) if result.avg_fill_price else None,
            }
            signal.execution_account = plan.execution_account

            logger.info(f"Executed {signal.action} for {signal.symbol}: {result.order_id}")

            # Notify execution handlers
            for handler in self._execution_handlers:
                handler(signal, plan)

        except Exception as e:
            logger.error(f"Failed to execute signal for {signal.symbol}: {e}")
            signal.execution_result = {"error": str(e)}

    def register_approval_handler(self, handler: Callable[[StrategySignal], bool]) -> None:
        """Register a handler for approval decisions."""
        self._approval_handlers.append(handler)

    def register_execution_handler(
        self, handler: Callable[[StrategySignal, ExecutionPlan], None]
    ) -> None:
        """Register a handler for execution events."""
        self._execution_handlers.append(handler)

    def create_strategy(
        self,
        name: str,
        description: str,
        symbols: List[str],
        **kwargs
    ) -> PlainLanguageStrategy:
        """Create and save a new strategy."""
        import uuid

        strategy = PlainLanguageStrategy(
            id=str(uuid.uuid4())[:8],
            name=name,
            description=description,
            symbols=symbols,
            **kwargs
        )

        self.repository.save(strategy)
        return strategy


# Singleton instance
_execution_engine: Optional[StrategyExecutionEngine] = None


def get_execution_engine(
    gemini_api_key: Optional[str] = None,
    model_api_keys: Optional[Dict[str, str]] = None,
    config_dir: str = "config/strategies"
) -> StrategyExecutionEngine:
    """Get or create singleton execution engine."""
    global _execution_engine

    if _execution_engine is None:
        if not gemini_api_key:
            raise ValueError("gemini_api_key required for initial setup")

        _execution_engine = StrategyExecutionEngine(
            gemini_api_key=gemini_api_key,
            model_api_keys=model_api_keys or {},
            config_dir=config_dir
        )

    return _execution_engine
